### ISSUE TITLE
Automate website build

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1177]
To automate the website build, the github action below may be used in addition to some modifications.

- Creation of the `gh-pages` branch whose updates will only be affected and set source website from this branch
- `webshot::install_phantomjs()` needs to be replaced by `webshot::install_phantomjs(force=TRUE)` to prevent crash when already installed and the function is called.

```yaml
name: pkgdown-dev
on:
  push:
    
jobs:
  pkgdown-dev:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Setup Pandoc for word conversion
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install ospsuite ecosystem and cran packages
        run: |
          Rscript .github/workflows/install_dependencies.R
      - name: Build dev site
        run: |
          pkgdown::build_site(install=TRUE)
        shell: Rscript {0}
     - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
```

For release site, it is possible to trigger only when `main` is merged by using:

```yaml
on:
  pull_request:
    branches:
      - main
    types:
      - closed
```

and, in the jobs, include the following in case the PR is closed without merging

```yaml
if: github.event.pull_request.merged == true)
```
