### ISSUE TITLE
Linux build: migrate from rClr to rSharp

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1228]

**Comment by pchelle** [comment]
I am not sure of the best option for this.
If I understand, we currently use a Docker Image for build/installation of the Reporting Engine to do this, correct ?

- [ ] Should we update the [Docker-Images-ReportingEngine](https://github.com/Open-Systems-Pharmacology/Docker-Images-ReportingEngine/tree/main) repo with installation of __rSharp__ ?
- [ ] Should we create a new github action or update `testRE.R` to build a Linux bundle ?
- [ ] Should we add use a similar pattern as the `ospsuite` package and use a [rake file](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/66eb79bca0f5aa1c70dc6ba0d071bbc24e0b1e76/appveyor-nightly.yml#L66-L73) ?

```yaml
after_test:
  - rake "create_linux_build[%APPVEYOR_BUILD_VERSION%, %APPVEYOR_BUILD_FOLDER%, ubuntu18]"
  - rake "create_linux_build[%APPVEYOR_BUILD_VERSION%, %APPVEYOR_BUILD_FOLDER%, centOS7]"
  - rake "download_portable[develop]"
  - appveyor PushArtifact "C:/projects/ospsuite-r/pksim_minimal.zip"
  - ps: copy ospsuite_*.zip ospsuite.zip
  - ps: copy ospsuite_*ubuntu18.tar.gz ospsuite_ubuntu18.tar.gz
  - ps: copy ospsuite_*centOS7.tar.gz ospsuite_centOS7.tar.gz
```
