### ISSUE TITLE
GH-Actions: change triggers

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1303]
Once fixed, I will archive the **main** branch and rename **develop** to **main**

* **update-release-website.yml**
Current trigger
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/fb6c04e4405cec36039c146c9fdbf99c3d148d1a/.github/workflows/update-release-website.yml#L5-L10
Should be changed to
```
on: 
  release:
    types: [released]
  pull_request:
```

* **update-dev-website.yml**
Current trigger
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/fb6c04e4405cec36039c146c9fdbf99c3d148d1a/.github/workflows/update-dev-website.yml#L2-L5
Should be changed to
```
on:
  push: 
    branches:
      - main
```
