### ISSUE TITLE
pkgdown: "standard" theme

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#707]
Let's set the theme of the online documentation to "standard" (dark text, white background)

Also some parts of the vignettes in the online documentation are not displayed correctly. 
Not sure if it's because of the theme or other settings

E.g. s. https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/introduction-re-instances.html#nomenclature

![grafik](https://user-images.githubusercontent.com/25061876/155174181-020d629b-dfad-452c-b642-dff64ecdc15e.png)

**Comment by IndrajeetPatil** [comment]
Change the following in [`_pkdown.yml`](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/_pkgdown.yml):

```yaml
template:
  bootstrap: 5
  bootswatch: cyborg
  theme: arrow-dark
  bslib:
    primary: "#0054AD"
    border-radius: 0.5rem
    btn-border-radius: 0.25rem
```

to

```yaml
template:
  bootstrap: 5
```

And then run:

```r
pkgdown::build_site()
```

Sorry, I can't build the website locally because there is something wrong with PK installation, so vignettes don't build.
